version: "3.3"

services:
  torrentHost:
    image: haugene/transmission-openvpn:3.3
    container_name: transmission
    restart: "no"
    privileged: true
    # dns:
      # - 8.8.8.8
      # - 8.8.4.4
    volumes:
      - trans-data:/data
      - .:/usr/src/app
      # - "$SOURCE_VOLUME:/data"
      # - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    healthcheck:
      disable: true
    # sysctls:
      # - net.ipv6.conf.all.disable_ipv6=0
      # - net.ipv6.conf.default.disable_ipv6=0
      # - net.ipv6.conf.lo.disable_ipv6=0
    # network_mode: bridge
    # logging:
    #   driver: json-file
    #   options:
    #     max-size: 10m
    ports:
      - 9091:9091
  torrentHelper:
    image: node:14
    restart: unless-stopped
    environment:
      - CONTAINERIZED=true
    env_file:
      - .env
    links:
      - "torrentHost:torrentHost"
    volumes:
      - .:/usr/src/app
    command: npm run --prefix /usr/src/app start:watch
volumes:
  trans-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=the-source.local,rw
      device: ":/volume1/video"