version: '3.3'

services:
  app:
    image: haugene/transmission-openvpn
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /volume1/video:/data
      - .:/usr/src/app
      - ./lib/resolv.conf:/etc/resolv.conf
      - /etc/localtime:/etc/localtime:ro 
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:                            
      - 9091:9091         
# Uncomment below to run a local web proxy
#proxy:
#  image: haugene/transmission-openvpn-proxy
#  links:
#    - transmission
#  ports:
#    - 8080:8080
#  volumes:
#    - /etc/localtime:/etc/localtime:ro