version: "3.3"

services:
  torrentHost:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: unless-stopped
    privileged: true
    dns:
      - 1.1.1.1
    volumes:
      - "$SOURCE_VOLUME:/data"
      - .:/usr/src/app
      - ./lib/resolv.conf:/etc/resolv.conf
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    cap_add:
     - NET_ADMIN
    ports:
      - 9091:9091
      - 8888:8888
  torrentHelper:
    image: node:8
    restart: unless-stopped
    environment:
      - CONTAINERIZED=true
    env_file:
      - .env
    links:
      - "torrentHost:torrentHost"
    volumes:
      - .:/usr/src/app
    command: npm run --prefix /usr/src/app start:watch