version: "3.3"

services:
  torrentHost:
    image: haugene/transmission-openvpn
    restart: unless-stopped
    dns:
      - 209.222.18.222
      - 209.222.18.218
    volumes:
      - "$SOURCE_VOLUME:/data"
      - .:/usr/src/app
      - ./lib/resolv.conf:/etc/resolv.conf
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    #devices:
      #- /dev/net/tun
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
  torrentHelper:
    image: node:8
    restart: unless-stopped
    environment:
      - CONTAINERIZED=true
    env_file:
      - .env
    links:
      - "torrentHost:torrentHost"
    volumes:
      - .:/usr/src/app
    command: npm run --prefix /usr/src/app start:watch
# Uncomment below to run a local web proxy
#proxy:
#  image: haugene/transmission-openvpn-proxy
#  links:
#    - transmission
#  ports:
#    - 8080:8080
#  volumes:
#    - /etc/localtime:/etc/localtime:ro
